### ISSUE TITLE
Adjust clouddriver's polling interval

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-spinnaker#100]
As a user, I want to adjust clouddriver's default polling level of 30 seconds to 5 minutes.

Set
```
redis.poll.intervalSeconds=300
```

**Comment by markpollack** [comment]
Addressed instead by changing the query via https://github.com/gregturn/clouddriver/blob/reactor/clouddriver-cf/src/main/groovy/com/netflix/spinnaker/clouddriver/cf/provider/agent/ClusterCachingAgent.groovy#L376
