### ISSUE TITLE
clouddriver/deck : Investigate supporting clone operations

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-spinnaker#103]

**Comment by gregturn** [comment]
Resolved via https://github.com/spinnaker/deck/commit/c1f8dbd86bcd66824a4875c6d6d46682e237d51d, https://github.com/spinnaker/deck/commit/5e261009e0612dd953f4b2f8dcc55fd2f78cc694, and https://github.com/spinnaker/clouddriver/commit/1c5776014ba15e09f1c05f071bb3eeca1f11a6a2
