### ISSUE TITLE
Compilation and Build failure while cleaning Maven package

### ISSUE THREAD

**Issue by jewel123** [spring-cloud/spring-cloud-spinnaker#18]
While trying to **build spinnaker** for Cloud foundry, we get compilation and build failure at the step for 
./mvnw clean package. We have used the latest repository '7279028ec456ea8e4f9483c647b69180e56d888c'. 
-------------------------------------------------------------------------------------------------------------------------------
Below are the details, 
[ERROR] /home/canopy/kiran/spring-cloud-spinnaker/src/main/java/org/springframework/cloud/spinnaker/DefaultAppDeployerFactory.java:[74,24] con
structor CloudFoundryAppDeployer in class org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryAppDeployer cannot be applied to given types;  
required: org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryDeployerProperties,org.cloudfoundry.operations.CloudFoundryOperati
ons,org.cloudfoundry.client.CloudFoundryClient,org.springframework.cloud.deployer.spi.cloudfoundry.AppNameGenerator
  found: org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryDeployerProperties,org.cloudfoundry.operations.CloudFoundryOperations
,org.cloudfoundry.client.CloudFoundryClient
  reason: actual and formal argument lists differ in length
-------------------------------------------------------------------------------------------------------------------------------
Couldn't find reference to AppNameGenerator anywhere in the repo. Could you please advice to proceed further. 

Also we observe that there are different .jar files for each modules in /target/ directory. Could you please guide or update readme, as per any additional steps to be followed (so as to get the settings tab to deploy other modules/apps).

**Comment by gregturn** [comment]
Duplicates #25

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-spinnaker/commit/ad48fb4baea00af5b470d43e4d3f01556336ad55
