### ISSUE TITLE
Migrate to using published uber JARs

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-spinnaker#2]
Once Netflix starts publishing echo-app, clouddriver-app, etc. uber JARs, migrate over to using them instead of building them here.

**Comment by gregturn** [comment]
Depends on #8

**Comment by markpollack** [comment]
To not be coupled to the spinnaker timeline, temporarily create and host our own artifacts.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-cloud/spring-cloud-spinnaker/commit/ef97dd89af9ba1cb96ae9593323fbc7e2f6fe410
