### ISSUE TITLE
Add multiple configs for clouddriver

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-spinnaker#23]
Create a 1-space, 2-space, and 3-space config file for clouddriver.

**Comment by gregturn** [comment]
Add several clouddriver.yml files to src/main/resources, and flag them for different profiles.

* clouddriver-one.yml
* clouddriver-two.yml
* clouddriver-three.yml

Then simply set the spring.profiles.active to one, two, or three based on choices made.

**Comment by gregturn** [comment]
Related to #77.

**Comment by markpollack** [comment]
Only keep #77 as we may alter the implementation approach based on supporting a newer version of spring boot.
