### ISSUE TITLE
Issue while deploying spinnaker apps

### ISSUE THREAD

**Issue by jewel123** [spring-cloud/spring-cloud-spinnaker#24]
Have deployed spinnaker successfully have filled in details for the  same in the settings page and clicked on deploy all ,but nothing seems to happen could you please suggest.

**Comment by gregturn** [comment]
Features to add:

1. Introduce more validation in the UX
2. Consider more error logging
3. Implement

**Comment by gregturn** [comment]
Closing since we're no longer investing in this project.
