### ISSUE TITLE
Issue raised earlier (#18) helped us push apps in our Environment. However only deck started successfully. Other apps dint start. Could you please advice.

### ISSUE THREAD

**Issue by jewel123** [spring-cloud/spring-cloud-spinnaker#32]

**Comment by gregturn** [comment]
You will have to fill out more details about what inputs you provided.

**Comment by gregturn** [comment]
Duplicates #24 

Please stop opening tickets just to get assistance with your installation. Gather details about your situation and put them in the ticket you already opened.
