### ISSUE TITLE
clouddriver: Add maven support to clouddriver deploy

### ISSUE THREAD

**Issue by gregturn** [spring-cloud/spring-cloud-spinnaker#39]
Right now, clouddriver-cf only supports web-based and S3-based artifacts. Add support to navigate to maven artifacts by coordinates.

NOTE: Also requires deck update.

**Comment by markpollack** [comment]
CAn use the support in spring cloud deployer.

**Comment by gregturn** [comment]
Closing since we're no longer investing in this project.
