### ISSUE TITLE
Only deck started successfully on pushing this app. Other apps did'nt started. Could you please advice.

### ISSUE THREAD

**Issue by rahul221191** [spring-cloud/spring-cloud-spinnaker#67]
Cloned from https://github.com/spring-cloud/spring-cloud-spinnaker repo.
I followed the readme docs to push this app on cloud-foundary and bind it to redis service.
But after deploying the app only deck started rest didn't.Could you please advice what went wrong while deploying it. 
 I am attaching the input which we provided in setting of spinnakar app.
![spinnakar-setting](https://cloud.githubusercontent.com/assets/16372337/17929447/3f4b0ba4-6a1e-11e6-928c-f089b36db667.png)
Attaching the output.
![app not running](https://cloud.githubusercontent.com/assets/16372337/17929516/a38f7942-6a1e-11e6-8f28-52b6fb6325ce.png).
could you please help us out.
Thanks in advance

**Comment by gregturn** [comment]
Drop the "*." prefix on your domain at the bottom.

If your target were desk-apps.cfapps.io, then you only entry "cfapps.io" in the domain field.

**Comment by ishwar1987** [comment]
Hi, Do you have documents for this?. How to configure all service component and how to use.

thanks in advance

**Comment by gregturn** [comment]
Sorry, but I haven't stopped to write documentation on this yet. It's a pending task, especially before this advanced to a GA release.

**Comment by ishwar1987** [comment]
Hi,
I am getting the following error in different component(App).
1)clouddriver
Error:The app package is invalid: bits have not been uploaded] with root cause

2)gete 
Its started but when i hit the url on browser then its redirect to  me on  http://localhost:9000/
and nothing displaying.

3)front50
its not started and its throwing an exception.

4)echo 
This is also not working. i have attached error message here.

I have attached error text file here. 
Thanks in advanced.
[Uploading Clouddriver log.txt…]()
[Echo.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/437620/Echo.txt)
[Front 50.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/437619/Front.50.txt)
[Gete.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/437621/Gete.txt)

**Comment by gregturn** [comment]
The echo bits only show 10 seconds. I promise you it takes longer than that to load.

It might be useful to gather logs from the instance of echo, etc. that you installed and post them here.

**Comment by rahul221191** [comment]
Now app echo is started and its showing 
![screen shot 08-26-16 at 12 46 pm](https://cloud.githubusercontent.com/assets/16372337/17997601/03cede46-6b8d-11e6-9be3-dd0a94fa54d9.PNG)

As asked i am Attaching the Echo log.please find the attachments.
[New Echo.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/438764/New.Echo.txt)

**Comment by gregturn** [comment]
The log files you are attaching are from spring-cloud-spinnaker and don't show me how echo, front50, etc. are starting. Instead, I need the logs from those apps, preferably showing a stack trace on launch.

All of the Spinnaker module apps happen to have Spring Data REST, which results in that "_links" HAL document getting shown if you visit /, so that screenshot isn't really that useful.

The key thing is to capture a log output from echo-app, front50-app, clouddriver-app, etc. and seeing the stack trace of failure which kills the container.

**Comment by ishwar1987** [comment]
The cloud driver is not starting. its giving an exception 
load java.util.ServiceConfigurationError: org.cloudfoundry.reconfiguration.org.springframework.cloud.service.ServiceConnectorCreator: Provider org.cloudfoundry.reconfiguration.org.springframework.cloud.service.smtp.MailSenderCreator could not be instantiated.
More information about this error we have attached here.

**Comment by gregturn** [comment]
Run "cf logs --recent clouddriver-app" and share with me, please.

**Comment by ishwar1987** [comment]
the thing is that the app itself is not getting  started.There is no instance of cloud-driver.
So we don't have any log to show for your particular app.
![cloud driver](https://cloud.githubusercontent.com/assets/7974404/18010882/13d51560-6bd0-11e6-88cf-6575017adb53.png)

**Comment by gregturn** [comment]
When you enter "apps" into the namespace field at the top, it tells the system to go and create clouddriver-apps, deck-apps, echo-apps, front50-apps, gate-apps, igor-apps, and orca-apps.

So I don't know what clouddriver is. A relic from a previous attempt at installation?

**Comment by ishwar1987** [comment]
Hi, while installing first time we have use name space "apps" but its crash. So I have reinstalled the everything without namespace.

**Comment by ishwar1987** [comment]
After deploy cloud driver its throwing the 
Failed to load java.util.ServiceConfigurationError: org.cloudfoundry.reconfiguration.org.springframework.cloud.service.ServiceConnectorCreator: Provider org.cloudfoundry.reconfiguration.org.springframe
work.cloud.service.keyval.RedisConnectionFactoryCreator could not be instantiated error. 

Even after binding the redis-service instance with spring-cloud-spinnaker.

Does i missing anything?

**Comment by gregturn** [comment]
I can't get very far unless you attempt a clean installation, and gather logs from the target app it's installing like clouddriver (not logs from spring-cloud-spinnaker). I need to see a full stack trace when the app starts and fails. From there, we can start to pick through things. Also, the "environment" tab for clouddriver should have LOTS of properties set. If there are none, then something has failed.

**Comment by ishwar1987** [comment]
Hi, I have done the clean installation.  I have follow the steps are.
1)Deploying spring-cloud-spinnaker  (Success)
2)I have updated the information on home page and i only click on the deploy the cloud driver which is not starting  and i have attached error file.
3)I have put the log in ModuleServices class which are:

		log.info("*** before invoking deploy method@@@@2");
		log.info("details.getName()"+details.getName()+namespace);
		log.info("properties "+properties);
		log.info("artifactToDeploy  "+artifactToDeploy);
		log.info("deploymentProperties  "+deploymentProperties);
		String deploymentId = appDeployer.deploy(new AppDeploymentRequest(
				new AppDefinition(details.getName() + namespace, properties),
				artifactToDeploy,
				deploymentProperties));

		log.info("*** After  invoking deploy method@@@@2");

This above logs in showing in the attach log file.
![spinnakerpic](https://cloud.githubusercontent.com/assets/7974404/18204919/f6943b4e-713c-11e6-85e4-ff3c8fa347a2.PNG)
[clouddriver.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/452077/clouddriver.txt)

Thanks in advanced.

**Comment by ishwar1987** [comment]
One more thing that the after failing cloud driver and if i use the 
cf_trace cloud driver
its giving following logs which i have attached log here.

**Comment by gregturn** [comment]
I still don't see a log file from clouddriver itself. That log file is from the deployer app. I cannot debug this without seeing what the clouddriver CF app is doing.

**Comment by ishwar1987** [comment]
Actually when i deploy the clouddrive i got this logger on cf console. So what other logs i will get and how?

**Comment by gregturn** [comment]
Run "cf logs --recent clouddriver" and share with me, please. We are trying to capture the startup of clouddriver.

**Comment by ishwar1987** [comment]
I need one more help how much memory size required to deploy this app?
Thanks in advanced.

**Comment by gregturn** [comment]
I don't follow. The deployer sets minimum required memory settings. We don't have memory overrides. You need to fetch the logs from clouddriver so we can debug that. Otherwise I'm blind to what's happening.

**Comment by rahul221191** [comment]
While deploying the app through console cloud driver logs were
[Cloud driver logs while deploying the cloud driver through console.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/456528/Cloud.driver.logs.while.deploying.the.cloud.driver.through.console.txt)

After deploying the cloud drive tried to trace:- 
CF_TRACE=TRUE cf restart clouddriver-apps log were

[CF_TRACE=TRUE.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/456535/CF_TRACE.TRUE.txt)

**Comment by gregturn** [comment]
The "cloud driver logs while deploying the cloud driver" log file is NOT clouddriver. It is the spring-cloud-deployer app. I can tell because I see "/api/modules" listed among the routes, and I see that it is Spring Boot 1.4.0, where clouddriver runs on Spring Boot 1.2.

I need to you do a "cf logs --recent clouddriver" trace in order to get log files I can deduce from. You keep sending me log files from spring-cloud-spinnaker, which aren't helping me spot what is misconfigured in clouddriver. Also, can you capture the Environment settings on clouddriver, and send them to me?

**Comment by gregturn** [comment]
Better yet, try this (after having installed clouddriver)

1. cf logs clouddriver
2. (In another shell) cf restart clouddriver
3. Capture the full output from clouddriver
4. Attach to this ticket.

**Comment by ishwar1987** [comment]
I have doubt on 3)steps.  Capture the full output from clouddriver? . Here you are talking about taking logs from console or from log files? if it's on log file then how do you know the location. please

**Comment by gregturn** [comment]
Run "cf logs clouddriver" so that it dumps out to the console. Copy-paste the stuff from Spring Boot's banner image to either "Started Main in xxx seconds" or until you see some stack trace into this ticket inside triple backticks.

**Comment by rahul221191** [comment]
The thing is cloud driver is not starting from so there is no way in which we can provide you the cloud driver log after pushing directly through the console.
Instead what we did was, we tried to pushing cloud Driver manually i.e. pushing the cloud driver jar file directly after downloading the JAR file.

**cf push clouddriver -p ./clouâÂ·Â·ddriver-web-1.24.0-SNAPSHOT.jar** 

When we checked the log we saw that it is some how dependent upon front-50 app which is showing from here what we got for
cf cloud-driver ---recent is:
[clouddriverlog.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/459181/clouddriverlog.txt)

**Comment by gregturn** [comment]
I think I see what has happened.

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'services.front50.basxxxrl' in string value "${services.front50.basxxxrl}"
```

When the deployer runs, it creates the following environment variable...

```
services.echo.baseUrl=${services.default.protocol}://${services.echo.host}${namespace}.${deck.domain}
```

Somehow, that variable name has changed. I am worried you went into the environment variables and accidentally renamed it.

If you look at https://github.com/spring-cloud/spring-cloud-spinnaker/blob/master/src/main/resources/application.yml, you can see almost all the properties that are set. There is a module-specific section marked **clouddriver** that lists some properties, while another section marked **properties** list most of them.

If you run "cf env clouddriver", and post a redacted list here, we can see exactly what needs to be fixed.

**Comment by gregturn** [comment]
clouddriver indeed depends on front50, but not for it to come up. What we are encountering is a broken property setting.

**Comment by ishwar1987** [comment]
The cf env clouddriver-app . it is displaying following values.
 "VCAP_APPLICATION": {
  "application_id": "xxxx-90e5-754d3d8caf4a",
  "application_name": "clouddriver-app",
  "application_uris": [],
  "application_version": "xxxx-16d9-4180-9ddb-f145b05a117b",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "clouddriver-app",
  "space_id": "620b6735-640a-44ad-bd87-3e8461d3bd11",
  "space_name": "ishwar-space",
  "uris": [],
  "users": null,
  "version": "xxxx-a-16d9-4180-9ddb-f145b05a117b"
 }
}
And clouddriver-app request state stop.

**Comment by gregturn** [comment]
I don't see any user provided env variables as is shown in this doc for "CF env". 
https://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html

**Comment by ishwar1987** [comment]
Evne "cf env spring-cloud-spinnaker" displaying same thing.
One more thing . After pushing the spring-cloud-spinnaker. The "cf env spring-cloud-spinnaker". its must be shown the user defined environment variable . Then  only the the clouddriver-app can access it right?. am i right?
if yes then basically problem is the pushing the spring-cloud-spinnaker app.

**Comment by gregturn** [comment]
"cf env foo" will dump out the environment settings for any app you point it at. 

I'm asking that you dump out the env settings from your clouddriver app and redact them, which is easier to convey through this ticket than trying to capture a few screenshots on the env tab of App Manager.

**Comment by ishwar1987** [comment]
The cf env clouddriver-app. Its not displaying any user defined variable.

**Comment by gregturn** [comment]
Can you run the command against the proper name (which I seem to lose track of), capture the entire output, and wrap it with triple backticks here?

**Comment by ishwar1987** [comment]
Actually we are trying with names space and without namespace thats why its app name is different.Nothing else different. and cf env cf env clouddriver-app. giving me the following output. This clouddriver-app we have deployed from the UI.

System-Provided:
{
 "VCAP_APPLICATION": {
  "application_id": "xxxx-538b-450f-90e5-754d3d8caf4a",
  "application_name": "clouddriver-app",
  "application_uris": [],
  "application_version": "xxxx-16d9-4180-9ddb-f145b05a117b",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "clouddriver-app",
  "space_id": "xxxx-640a-44ad-bd87-3e8461d3bd11",
  "space_name": "ishwar-space",
  "uris": [],
  "users": null,
  "version": "xxxx-16d9-4180-9ddb-f145b05a117b"
 }
}
No user-defined env variables have been set
No running env variables have been set
No staging env variables have been set

**Comment by gregturn** [comment]
Okay, this tells me that clouddriver did not deploy successfully. front50 looks good, so far, with all it's env variables. I would attempt to undeploy then redeploy clouddriver with all your settings. Every single Spinnaker component will have user-defined env variables.

**Comment by ishwar1987** [comment]
Hi.
I have clean and tried. The all  services successfully deployed except the clouddriver. whenever i deploying clouddriver i am getting the following exception.

OUT App instance exited with guid xxxxx-cf6e-4434-ad9f-877e7fcee6f0 payload: {
"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n*
Exited with status 255 (out of memory)\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>147566929581027807
3, "version"=>"f7c37d96-7961-4a47-a1dc-099494ae055d"}


So i have trying another way to push cloud driver using the manifest file where the clouddriver jar file is exist. but when i try to do cf push with attached manifest then i am 
getting following exception.
Property '${namespace}' found in manifest. This feature is no longer supported. Please remove it and try again.

I have attached manifest.yml here for clouddriver.

The my org contains  30GB disk and  1GB Memory(This will allocated 1GB memory to each application which is push in this org).


[clouddrivermanifest.txt](https://github.com/spring-cloud/spring-cloud-spinnaker/files/511141/clouddrivermanifest.txt)

**Comment by gregturn** [comment]
Clouddriver needs 4G memory and 2G disk. That is what the deployer configures.

**Comment by gregturn** [comment]
And what do you mean deployed with a manifest? That file is not a CF manifest that works with the CLI. It's a set of app properties used by spring cloud spinnaker.

**Comment by ishwar1987** [comment]
I have use this manifest file format to deploy the other application.   So i have use same format for clouddriver and i have specified the environment variable too.

**Comment by gregturn** [comment]
I can't guarantee anything because you're using a file meant for the app instead with the CF CLI. 

Also, the deployer app actually adds a property file to each jar before pushing to PCF, so if you manually push things, I can't guarantee it working.

I have no clue what your environment looks like unless you are able to let me see it somehow.

**Comment by ishwar1987** [comment]
is there any way that i can explicitly specify the 4GB Ram for clouddriver? .

**Comment by gregturn** [comment]
cf scale -m 4G

**Comment by ishwar1987** [comment]
Hi,
After allocated the 4G memory and 2G Disk to cloud driver. Its failing with out of memory error. I have attached screen shot here. 
![upspinnaker](https://cloud.githubusercontent.com/assets/7974404/19474771/b38ecff4-954e-11e6-8cb0-11a1ab3a8f47.PNG)

Any suggestion.
Thanks in advanced.

**Comment by markpollack** [comment]
It seems you are directly pushing the apps that get created by the spring-cloud-spinnaker app, is that correct?  That generally isn't what we want to support, though we are going to start to host our own uber-jar artifacts that should clean up this process considerably.  See https://github.com/spring-cloud/spring-cloud-spinnaker/issues/2

Can you post any logs wrt to the out of memory error?   Are you getting a 137 error code in the logs?  We have observed that error in some cases on Spring Cloud Data Flow (though frankly the 4GB, even when translated to JVM memory allocated on PCF) should be a decent amount.  Alternatively, are you seeing a ` java.lang.OutOfMemoryError`?

**Comment by ishwar1987** [comment]
HI,
I am deploying the all jars using the spinnaker Application.  I am getting following exception:

OUT App instance exited with guid xxxxx-cf6e-4434-ad9f-877e7fcee6f0 payload: {
"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n*
Exited with status 255 (out of memory)\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>147566929581027807
3, "version"=>"f7c37d96-7961-4a47-a1dc-099494ae055d"}

Note: The my cloud foundry manifest contain the default memory 1GB Memory and 1GB Hard disk.

**Comment by gregturn** [comment]
I don't understand what you mean by "cloud foundry manifest". We aren't using manifest files for this.

**Comment by gregturn** [comment]
Okay, I just deployed clouddriver testing something else, and spotted the same memory issue.

**Comment by gregturn** [comment]
Based on https://github.com/spring-cloud/spring-cloud-spinnaker/commit/2488ccbbe9afb4e69ac12b205b23212009b19e48 I'm going to consider this issue resolved.

If you have new issues, feel free to open new tickets, okay? Thanks for taking a turn at everything.
