### ISSUE TITLE
Installation failed due to maven-frontend-plugin: 

### ISSUE THREAD

**Issue by bjornharvold** [spring-cloud/spring-cloud-spinnaker#74]
When running ./mvnw clean package I get this error:
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:bower (bower install) on project spring-cloud-spinnaker: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]

I have tried upgrading the frontend-maven-plugin to 1.0 but with the same result.

**Comment by gregturn** [comment]
Possible duplicate of https://github.com/spring-cloud/spring-cloud-spinnaker/pull/73. Can you recheck against the latest?

**Comment by bjornharvold** [comment]
This error got fixed after updating to latest.

**Comment by gregturn** [comment]
Good!
