### ISSUE TITLE
Support login to Spinnaker UI via PCF/PWS UAA OAuth provder

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-spinnaker#78]

**Comment by gregturn** [comment]
Contact Gunnar to get details and make it this an option (not a requirement)

**Comment by gregturn** [comment]
Related to #44

**Comment by gregturn** [comment]
Gunnar says PWS by itself isn't adequate as an OAuth provider, so pushing this out of the 1.0 release plans.

**Comment by gregturn** [comment]
Closing since we're no longer investing in this project.
