### ISSUE TITLE
Simplify initial installation with more default values.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-spinnaker#79]
For example, if there are existing redis service in the space, we can prepopulate the drop box that selects the redis service for spinnaker components to use.

**Comment by gregturn** [comment]
I think biggest thing we can help with here is finding existing redis instances, and possibly offering to create a new one if none is found in the same space.

Brainstorming, we could spot if the API URL is PWS, and if so, pre-populate the console link.

**Comment by gregturn** [comment]
#84 helps by making redis a drop down selection (of existing ones)

**Comment by gregturn** [comment]
#84 lets you pick Redis instance from a dropdown
#85 sniffs the API entered, and if its PWS, pre-prepopulates the console URL. Also includes hyperlinks to create Slack BOT tokens and Travis Github tokens
#86 makes picking org/space drop downs after entering credentials
#87 shows a spinner while the various drop downs are being populated
