### ISSUE TITLE
Improve handling of spinnaker resource files in non-standard directory

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-spinnaker#80]
The current implementation unpacks jar files in memory and shifts the resource files into a spot that boot expects, then makes a new jar.  Since this occurs in memory, the memory requirements for the app are very large - 8GB.

We should  

1) switch to use tmp files 

or 

2) host our own uber-jar that is packaged correctly.

#2 is the preferred solution for RC/GA.

Spinnaker core dev team may adopt #2 themselves, so look to coordinate with them.

**Comment by gregturn** [comment]
Possibly overcome by https://github.com/spring-cloud/spring-cloud-spinnaker/pull/61. That PR updated to a stable version of cf-java-client that required Resource's that could resolve to hard files.

I implemented a service that would create a classic temp file, but includes a delete operation to thus not wait for the container to shutdown and clean out temp files (cloud native requirement is to not wait for container to shut down).

**Comment by gregturn** [comment]
Part 1 has already been implemented.

**Comment by markpollack** [comment]
Part 1 commited as 0eec3e19ae21a58e910cbf5665cbfdeba6388542.

See #2 for the other issue of uber-jar hosting/packaging.
