### ISSUE TITLE
After converting jar file to war file its throwing an error.

### ISSUE THREAD

**Issue by ishwar1987** [spring-cloud/spring-cloud-spinnaker#88]
Hi,
I have downloaded the full code and i have modified and generated war file for deploy on local tomcat server. The last week its was working . Today when i done the following commands.
./mvnw clean package.

It is not working. Actually things it is happen that when i click on the load button . it is sending request to server like following format.
 GET http://localhost:8080/api?api=https://api.sys.eu.cfdev.canopy-cloud.com&org…r-space&email=Test&password=testpassword&namespace=-app 404 (Not Found)

The actually its not adding the project name. 

This above things displaying in google chrome browser console.
I have generated the war file using the http://docs.spring.io/spring-boot/docs/current/reference/html/build-tool-plugins-maven-plugin.html.

Thanks in advanced.

**Comment by gregturn** [comment]
I've never run a Spring HATEOAS-based project from a WAR so I don't know the exact source of the issue. This is a configuration we aren't ready to support yet so don't expect prompt response on it.

**Comment by ishwar1987** [comment]
Hi, 
while doing ./mvnw clean package. 
its showing an 
ERROR] bower   invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

But BUILD SUCCESS.
is there any problem?

**Comment by gregturn** [comment]
No. It's just a warning, one that I removed in https://github.com/spring-cloud/spring-cloud-spinnaker/commit/9745a259c6d77eaed5eb8e2d7100abf5aa44a27c

**Comment by gregturn** [comment]
Closing since we're no longer investing in this project.
